name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest

  services:
    postgres:
      image: postgres
      env:
        POSTGRES_PASSWORD: 123456
        POSTGRES_USER: team
        POSTGRES_DB: test
        POSTGRES_PORT: 5432

      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: install dependancies
      run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        TEST_DATABASE_URL: postgres://team:123456@localhost:5432/test
